server:
  port: 9000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: reactive-social-application-comments
          group:  comments-service
          content-type: application/json
        output:
          destination: reactive-social-application-chat
          group: comments-chat
          content-type: application/json


  devtools:
    restart:
      log-condition-evaluation-delta: false

logging:
  level:
    web: DEBUG
    reactor:
      core: TRACE
      util: TRACE
    org:
      springframework:
        cloud: DEBUG
        integration: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health