eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  servlet:
    multipart:
      max-file-size: 10MB

  cloud:
    stream:
      bindings:
        input:
          destination:  reactive-social-application
        output:
          destination:  reactive-social-application
          group:  comments
          content-type: application/json

  devtools:
    restart:
      log-condition-evaluation-delta: false

logging:
  level:
    web: DEBUG
    reactor:
      core: TRACE
      util: TRACE
    org:
      springframework:
        cloud: DEBUG
        integration: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health